### ISSUE TITLE
Many duplicate NestedHasMany elements get created when using Turbolinks

### ISSUE THREAD

**Issue by sedubois** [zooppa/administrate-field-simple_markdown#16]
Since using this gem, several instances of my [NestedHasMany](https://github.com/nickcharlton/administrate-field-nested_has_many) nested resources get created whenever clicking "Add Program/Translation". 

See illustration before clicking (I removed the fields in the nested resource for conciseness):

<img width="1387" alt="Screenshot 2020-04-24 at 11 57 51" src="https://user-images.githubusercontent.com/4217871/80200461-f2e00880-8622-11ea-8808-838eea7ef542.png">

And after clicking:

<img width="1377" alt="Screenshot 2020-04-24 at 12 08 55" src="https://user-images.githubusercontent.com/4217871/80201419-646c8680-8624-11ea-98ce-c3f91d1d4687.png">

The number of duplicate boxes corresponds to the number of page navigations that have been performed by Turbolinks since the last full page load. E.g if I visit 2 other pages using my side navigation, then visit the Programs index, then click "New Program", then click "Add Program/Translation", then there will be 4 instances of the nested resource.

When commenting out `turbolinks.start()` in Javascript, the issue disappears.

NB: the issue is completely unrelated to whether there are actual `Field::SimpleMarkdown` used in dashboards. Just having the gem in the gemfile (and thus its Javascript loaded in the asset pipeline) is enough to get the issue.

It makes for a poor admin experience, but more importantly it also breaks the tests. Is there any way to make this gem work with Turbolinks?

Using administrate-field-simple_markdown 0.3.0, administrate-field-nested_has_many 1.2.0@bbc3cb777b.

**Comment by michelegera** [comment]
Hi @sedubois and once again apologies for the late response.

It seems clear to me that the feature to support interactions with NestedHasMany and/or Turbolinks is severely broken and since I don’t have bandwidth to dig into it and work on a fix, I’ve decided to revert the logic to HTML IDs and [release a new version](https://github.com/zooppa/administrate-field-simple_markdown/releases/tag/v0.4.0) that at least ensures compatibility with basic scenarios.

Unfortunately I won’t be able to maintain this gem anymore, so if you or someone else wants to take over, I’d be happy to transfer the repository ownership.

I’m sorry for the hassle (and the wait!).

**Comment by sedubois** [comment]
Thank you @michelegera, understood. I am still considering migrating my markdown fields to ActionText, which would solve the issue. Thanks for all your work so far and all the best.
